/*
 * File: out_leg_speed.c
 *
 * MATLAB Coder version            : 5.3
 * C/C++ source code generated on  : 12-Dec-2023 12:35:07
 */

/* Include Files */
#include "out_leg_speed.h"
#include <math.h>

/* Function Definitions */
/*
 * OUT_LEG_SPEED
 *     SPEED = OUT_LEG_SPEED(D_PHI1,D_PHI4,PHI1,PHI4)
 *
 * Arguments    : float d_phi1
 *                float d_phi4
 *                float phi1
 *                float phi4
 *                float speed[2]
 * Return Type  : void
 */
void out_leg_speed(float d_phi1, float d_phi4, float phi1, float phi4,
                   float speed[2])
{
  float t10_tmp;
  float t12_tmp;
  float t2;
  float t21;
  float t22;
  float t23;
  float t24;
  float t28;
  float t3;
  float t30;
  float t32;
  float t38;
  float t4;
  float t44;
  float t47;
  float t48;
  float t5;
  float t52;
  float t53;
  float t59;
  float t60;
  float t70;
  float t71;
  float t76;
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     11-Dec-2023 21:37:12 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10_tmp = t2 / 20.0F;
  t12_tmp = t4 / 20.0F;
  t21 = t2 * 0.0105F;
  t22 = t3 * 0.0105F;
  t23 = t4 * 0.0105F;
  t24 = t5 * 0.0105F;
  t28 = t12_tmp + -(t5 / 20.0F);
  t30 = (t3 / 20.0F + -t10_tmp) + 0.06F;
  t32 = t23 + -t24;
  t38 = (t22 + -t21) + 0.0126F;
  t44 = t28 * t28 + t30 * t30;
  t47 = t2 * t28 / 10.0F + t4 * t30 / 10.0F;
  t48 = t3 * t28 / 10.0F + t5 * t30 / 10.0F;
  t52 = 1.0F / (t38 + t44);
  t53 = t52 * t52;
  t59 = sqrtf((t32 * t32 + t38 * t38) + -(t44 * t44));
  t60 = 1.0F / t59;
  t30 = (t24 + -t23) + t59;
  t28 = atanf(t52 * t30) * 2.0F;
  t70 = cosf(t28);
  t71 = sinf(t28);
  t76 = 1.0F / (t53 * (t30 * t30) + 1.0F);
  t47 =
      (t23 + t47) * t53 * t30 +
      t52 * (t21 +
             -(t60 *
               ((t2 * t32 * 0.021F + t4 * t38 * 0.021F) + -(t44 * t47 * 2.0F)) /
               2.0F));
  t28 =
      (t24 + t48) * t53 * t30 +
      t52 * (t22 +
             -(t60 *
               ((t3 * t32 * 0.021F + t5 * t38 * 0.021F) + -(t44 * t48 * 2.0F)) /
               2.0F));
  t4 = t12_tmp + t71 * 0.105F;
  t21 = (t10_tmp + t70 * 0.105F) - 0.03F;
  t59 = t70 * t76;
  t23 = t59 * t28;
  t53 = t71 * t76;
  t2 = t53 * t28;
  t28 = (-t10_tmp + -(t70 * 0.105F)) + 0.03F;
  t60 = t28 * t28;
  t52 = 1.0F / t28;
  t30 = t4 * t4;
  t28 = 1.0F / sqrtf(t30 + t21 * t21);
  t48 = 1.0F / (t30 + t60);
  t59 = t10_tmp - t59 * t47 * 0.21F;
  t30 = t12_tmp - t53 * t47 * 0.21F;
  speed[0] = d_phi4 * t28 * (t4 * t23 * 0.42F - t21 * t2 * 0.42F) / 2.0F +
             d_phi1 * t28 * (t4 * t59 * 2.0F - t21 * t30 * 2.0F) / 2.0F;
  t28 = t4 * (1.0F / t60);
  speed[1] =
      d_phi4 * t60 * t48 * (t52 * (0.0F - t23 * 0.21F) + t28 * (t2 * 0.21F)) -
      d_phi1 * t60 * t48 * (t52 * t59 - t28 * t30);
}

/*
 * File trailer for out_leg_speed.c
 *
 * [EOF]
 */
