/*
 * File: out_leg_position.c
 *
 * MATLAB Coder version            : 5.3
 * C/C++ source code generated on  : 17-Dec-2023 22:40:34
 */

/* Include Files */
#include "out_leg_position.h"
#include <math.h>

/* Function Definitions */
/*
 * OUT_LEG_POSITION
 *     POS = OUT_LEG_POSITION(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float pos[2]
 * Return Type  : void
 */
void out_leg_position(float phi1, float phi4, float pos[2])
{
  float a;
  float b_a;
  float t14;
  float t15;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  float t8_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     17-Dec-2023 22:37:02 */
  t2 = (float)cos(phi1);
  t3 = (float)cos(phi4);
  t4 = (float)sin(phi1);
  t5 = (float)sin(phi4);
  t6 = t2 / 20.0F;
  t8_tmp = t4 / 20.0F;
  t14 = t4 * 0.0105F;
  t15 = t5 * 0.0105F;
  t5 = t8_tmp + -(t5 / 20.0F);
  a = (t3 / 20.0F + -t6) + 0.06F;
  b_a = t14 + -t15;
  t4 = (t3 * 0.0105F + -(t2 * 0.0105F)) + 0.0126F;
  t5 = t5 * t5 + a * a;
  t4 = (float)atan(
           1.0F / (t4 + t5) *
           ((t15 + -t14) + (float)sqrt((b_a * b_a + t4 * t4) + -(t5 * t5)))) *
       2.0F;
  t5 = t8_tmp + (float)sin(t4) * 0.105F;
  t4 = (t6 + (float)cos(t4) * 0.105F) - 0.03F;
  pos[0] = (float)sqrt(t5 * t5 + t4 * t4);
  pos[1] = (float)atan2(t5, t4);
}

/*
 * File trailer for out_leg_position.c
 *
 * [EOF]
 */
