/*
 * File: out_lqr_k.c
 *
 * MATLAB Coder version            : 5.3
 * C/C++ source code generated on  : 10-Apr-2024 09:54:10
 */

/* Include Files */
#include "out_lqr_k.h"
#include "out_lqr_k_data.h"
#include "out_lqr_k_initialize.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static float rt_powf_snf(float u0, float u1);

/* Function Definitions */
/*
 * Arguments    : float u0
 *                float u1
 * Return Type  : float
 */
static float rt_powf_snf(float u0, float u1)
{
  float f;
  float f1;
  float y;
  if (rtIsNaNF(u0) || rtIsNaNF(u1)) {
    y = rtNaNF;
  } else {
    f = (float)fabs(u0);
    f1 = (float)fabs(u1);
    if (rtIsInfF(u1)) {
      if (f == 1.0F) {
        y = 1.0F;
      } else if (f > 1.0F) {
        if (u1 > 0.0F) {
          y = rtInfF;
        } else {
          y = 0.0F;
        }
      } else if (u1 > 0.0F) {
        y = 0.0F;
      } else {
        y = rtInfF;
      }
    } else if (f1 == 0.0F) {
      y = 1.0F;
    } else if (f1 == 1.0F) {
      if (u1 > 0.0F) {
        y = u0;
      } else {
        y = 1.0F / u0;
      }
    } else if (u1 == 2.0F) {
      y = u0 * u0;
    } else if ((u1 == 0.5F) && (u0 >= 0.0F)) {
      y = (float)sqrt(u0);
    } else if ((u0 < 0.0F) && (u1 > (float)floor(u1))) {
      y = rtNaNF;
    } else {
      y = (float)pow(u0, u1);
    }
  }
  return y;
}

/*
 * OUT_LQR_K
 *     K = OUT_LQR_K(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
void out_lqr_k(float L0, float K[12])
{
  float t2;
  float t3;
  if (!isInitialized_out_lqr_k) {
    out_lqr_k_initialize();
  }
  /*     This function was generated by the Symbolic Math Toolbox version 9.0.
   */
  /*     10-Apr-2024 09:53:40 */
  t2 = L0 * L0;
  t3 = rt_powf_snf(L0, 3.0F);
  K[0] = ((L0 * -3.76674342F - t2 * 38.1215744F) + t3 * 79.1546631F) -
         0.0273834337F;
  K[1] = ((L0 * 0.104593188F + t2 * 0.44012177F) - t3 * 2.4934454F) -
         0.0119181192F;
  K[2] =
      ((L0 * -0.293155849F - t2 * 6.88714314F) + t3 * 8.5981F) - 0.00187363429F;
  K[3] = ((L0 * 0.00805190671F + t2 * 0.0280311853F) - t3 * 0.0981052294F) -
         6.68742869E-5F;
  K[4] =
      ((L0 * -2.79273343F - t2 * 16.4593887F) + t3 * 57.1978455F) + 0.02329503F;
  K[5] = ((L0 * -0.105483748F + t2 * 0.601350665F) - t3 * 1.59801948F) +
         0.0255732369F;
  K[6] = ((L0 * -2.03871536F - t2 * 15.2830858F) + t3 * 47.064537F) -
         0.00178994483F;
  K[7] =
      ((L0 * 0.0833286F - t2 * 0.54431F) + t3 * 1.28753865F) + 0.00517466431F;
  K[8] = ((L0 * -15.3955994F + t2 * 96.6254F) - t3 * 239.920746F) + 1.29527569F;
  K[9] =
      ((L0 * 0.471250772F - t2 * 3.52265286F) + t3 * 9.50673866F) + 1.52404106F;
  K[10] =
      ((L0 * -0.75414747F + t2 * 4.84687F) - t3 * 12.2040758F) + 0.0653080419F;
  K[11] = ((L0 * 0.00556098903F - t2 * 0.0384764597F) + t3 * 0.100472301F) +
          0.0766970366F;
}

/*
 * File trailer for out_lqr_k.c
 *
 * [EOF]
 */
